---
name: Octoscan Workflow Security

on:
  workflow_dispatch:
  
  pull_request:
    paths:
      - '.github/workflows/**'
  
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'

jobs:
  octoscan:
    uses: huggingface/security-workflows/.github/workflows/octoscan-reusable.yml@main
    permissions:
      security-events: write
      actions: read
      contents: read
    with:
      target: '.github/workflows' # Target directory (default: .github/workflows)
      disable_rules: 'shellcheck,local-action,runner-label' # Rules to disable 
      filter_triggers: '' # Filter by triggers (empty = scan all, 'external' = only external triggers)
      generate_summary: true