---
name: Reusable Permissions Advisor

on:
  workflow_call:
    inputs:
      workflow_name:
        description: 'Workflow file to analyze'
        required: false
        type: string
        default: ''
      run_count:
        description: 'Number of runs to analyze'
        required: false
        type: number
        default: 10

permissions:
  actions: read
  contents: read

jobs:
  advisor:
    name: Analyze Permissions
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      
      - name: Run Advisor
        uses: GitHubSecurityLab/actions-permissions/advisor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9
        with:
          name: ${{ inputs.workflow_name }}
          count: ${{ inputs.run_count }}
