name: security-validate
on: 
  - pull_request
  - workflow_dispatch
jobs:
  validate:
    uses: huggingface/deny-actions-registry/.github/workflows/validate.yml@60d5719f7b43460684e1989c696c941a89a3c49d
