---
name: Reusable GitHub Actions Security Analysis with zizmor 🌈

on:
  workflow_call:
    inputs:
      sarif_category:
        description: 'SARIF category name'
        required: false
        type: string
        default: 'zizmor'
      workflow_paths:
        description: 'Path to workflows directory'
        required: false
        type: string
        default: '.github/workflows'

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  zizmor:
    name: zizmor analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
      
      - name: Run zizmor 🌈
        run: uvx zizmor --config zizmor/.zizmor.yml --format=sarif "$WORKFLOW_PATHS" > results.sarif 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_PATHS: ${{ inputs.workflow_paths }}
      
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@b96794f015dfd88f77b49b1c93e0fa7110f94c63 # v4.38.0
        with:
          sarif_file: results.sarif
          category: ${{ inputs.sarif_category }}